config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :categories do
    resources :transactions
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "categories#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions

  include ImageUploader::Attachment(:icon)
  validates :name, presence: true
  #   validates :icon, presence: true, length: { maximum: 300 }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :amouunt, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :transactions

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
# controllers for categories
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[home]
  # GET /categories or /categories.json
  def index
    @categories = Category.all
    # @total_amount = 0
    # @categories.each do |c|
    #   @total_amount += Transaction.find(:total).where(category_id: c.id)
    # end
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end
  def home; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_url
      # format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      # format.json { render :show, status: :created, location: @category }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @category.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/transactions_controller.rb
# controllers for transactions
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.includes(:category).where(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @category = Category.find(params[:category_id])

    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = current_user.transactions.build(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html do
          redirect_to category_transactions_url(@transaction.category_id),
                      notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amouunt, :category_id)
  end
end

app/controllers/users_controller.rb
# controllers for users
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
# application helper
module ApplicationHelper
end

app/helpers/categories_helper.rb
# categories helper
module CategoriesHelper
end

app/helpers/transactions_helper.rb
# transactions helper
module TransactionsHelper
end

app/helpers/users_helper.rb
# users helper
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>
  <p>
    <strong>Transaction Amount:</strong>
    <%# <%= total_amount %> 
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block", class: "form-label" %>
      <%= image_tag form.category.icon_url if category.cached_icon_data %>
      <%= form.hidden_field :icon, value: category.cached_icon_data %> 
    <%= form.file_field :icon, class: "form-control"%>
  </div>

  <div>
    <%= form.submit "Save Category", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/home.html.erb
<div class="container" style = "background-image: url('../../assets/images/background2.jpg')">
<div class="brand" style="text-align: center">
<%=  image_tag "chart.jpg" %>
<h2 style= "margin-top: -50px; font-size: 10vw" class="">BUDGET APP</h2>
</div>
<div class= "row" style="text-align: center">
<div class="col">
<%= button_to "LOG IN", new_user_session_path, class: "btn btn-primary mt-4"%> 
</div>
<div class="col">
<%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary mt-4"%>
</div>
</div>
</div>

app/views/categories/index.html.erb
<div style="text-align: center; padding: 8px 0">
<h1>Categories</h1>
</div>

<div id="categories">
  <% @categories.each do |category| %>
  <% total_amount = Transaction.where(category_id: category.id).sum(:amouunt)%>
    <div id="<%= dom_id category %>" class="mt-2"
    style="min-height: 90px;
    box-shadow: 0 0 15px 0 #888;
    padding: 0 24px;
    display: flex;
    align-items: center;


   
    ">
    <a href="/categories/<%= category.id%>/transactions" 
    style="text-decoration: none;
    color: #434b54;
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    ">
       <p style="width: 15vw;height: 15vw; border: 1px solid">
        <%= image_tag category.icon_url,style: "width: 100%; height: auto" if category.icon%>
      </p>

      <p>
        <%= category.name %>
      </p>

      
      <p>
         <%= number_to_currency(total_amount, :unit => "$")%> 
      </p></a>
    </div>
 
  <% end %>
</div>

<div style="
min-height: 60px;
border: 1px solid;
display: flex;
align-items: center;
justify-content: center;
background: #5fb523;
padding: 12px;
margin-top: 5px;
">
<a href= "/categories/new" style="
text-decoration: none;
color: white;
padding: 8px 24px;
border: 1px solid white;
">New Category
</a></div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

<br>

<div>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
  
    <main>
      <%= render 'shared/navbar' %>
        <div class="max-w-9xl mx-auto px-4 py-2 sm:px-6 lg:px-8 ">
        <div class="mx-auto max-w-9xl ">
          <%= yield %>
        </div>
        </div>
    </main>


  </body>
</html>

app/views/shared/_navbar.html.erb
 <% if current_user %>
<div class="w-full dark:text-white">
  <div >
    <nav style="background: #3778c2; min-height: 70px; display: flex; padding: 0 24px; align-items: center; justify-content: space-between;">
          <div class="">
            <%=link_to "<", 'javascript:history.back()', style: "color: white; text-decoration: none;font-weight: bolder;font-size: 8vw" %>
          </div>
          <div class="" >
            <%=link_to "Logout", destroy_user_session_path, method: :delete, style: "color: white; text-decoration: none;font-weight: 400;font-size: 5vw" %>
          </div>
        
    </nav>
  </div>
</div>
<% end %>

app/views/transactions/_form.html.erb
<%= form_with model: @transaction, path: category_transactions_path,method: :post do |form| %>
  <% if @transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% @transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
      <%= form.label :category, style: "display: block" %>
      <%= form.select:category_id, options_for_select(@categories),{include_blank: "Select Category"},{required: true, class: "form-select "} %>   
   </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amouunt %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="mt-2"
    style="min-height: 90px;
    box-shadow: 0 0 15px 0 #888;
    padding: 0 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    ">
  <p>
    <b><%= transaction.name %></b>
  </p>

  <p>
    <strong>
    <%= number_to_currency(transaction.amouunt, :unit => "$")%> 
    </strong>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<div style="
min-height: 60px;
display: flex;
align-items: center;
justify-content: space-between;
padding: 0 20px;
border-bottom: 1px solid;
">
<strong>
<%= @category.name%>
</strong>
<strong>
<% total_amount = Transaction.where(category_id: @category.id).sum(:amouunt)%>
<%= number_to_currency(total_amount, :unit => "$")%>
</strong>
</div>
<div style="text-align: center; padding: 8px 0">
<h1>Transactions</h1>
</div>
<div id="transactions">
  <% @transactions.includes(:category).each do |transaction| %>
    <%= render transaction %>
    <p>
      <%# <%= link_to "Show this transaction", category_transaction_path(transaction.category_id,transaction) %>
    </p>
  <% end %>
</div>
<div style="
min-height: 60px;
border: 1px solid;
display: flex;
align-items: center;
justify-content: center;
background: #5fb523;
padding: 12px;
">
<a href= "/categories/<%= @category.id%>/transactions/new" style="
text-decoration: none;
color: white;
padding: 8px 24px;
border: 1px solid white;
">New transaction
</a></div>

app/views/transactions/new.html.erb
<strong><h2><%= @category.name%></h2></strong>
<%= form_with model: @transaction, url: category_transactions_url do |form| %>
  <% if @transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% @transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
    <%= form.hidden_field :category_id, value: @category.id %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block", class: "form-label" %>
    <%= form.number_field :amouunt, class: "form-control" %>
  </div>
 <div class="alet">
    <p class="notice"><%= notice%></p>
    <p class="alert"><%= alert%></p>
  </div>
  <div>
    <%= form.submit "Save Transaction", class: "btn btn-primary mt-1 col" %>
  </div>
<% end %>

<br>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Back to transactions", category_transactions_path(@transaction.category_id) %>

  <%# <%= button_to "Destroy this transaction", @transaction, method: :delete %> 
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>